apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: gitops
  name: flask-app-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app-container
        image: krrish1110/gitops-demo-app:6
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  namespace: gitops
  name: flask-app-svc
spec:
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: flask-app
---
  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    namespace: gitops
    name: flask-app-ingress
  spec:
    ingressClassName: nginx
    rules:
    - host: gitops.bbros.xyz
      http:
          paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flask-app
                port:
                  number: 80
